### ISSUE TITLE
Playlist-sidene: Restriksjon på oppgaver 

### ISSUE THREAD

**Issue by kristandre** [NorwegianKiwi/codeclub-viewer#100]
> Vise ikoner ved siden av de oppgavene som har bestemte restriksjoner (Arve skriver "Dette er enkelt med tags. Hvis det finnes et ikon med samme navn som tagg "windows.png" --> vis ikon"), f.eks.
Virker ikke på nettbrett
Krever Windows OS
Trenger en betalt konto (e.g. minecraft)
Oppgaver som krever ekstrautstyr, arduino, raspberry pi

Er det tenkt at disse restriksjonene skal være en del av vanlige tags? Eller skal dette være en egen greie? Skal de vises i filteret? Gir det mening å filtrere slik at det kun vises oppgaver som koster penger f.eks? For restriksjoner må man kanskje kunne filtere omvendt av hvordan man filterer på vanlige tags; f.eks ikke vis oppgaver med restriksjoner 'koster penger', 'bare windows', etc.

Jeg har sett for meg at det blir noe som det her:
```
---
tags:
  tema: [lag spill]
  plattform: [windows, browser]
  fag: [engelsk, lesing]
restrictions: [koster penger, ikke ipad, bare windows]
---
```
